# Generated by Django 4.2.9 on 2026-02-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leavetype_leaveapplication'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date'], name='student_att_date_1ee40f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['school', 'date', 'status'], name='student_att_school__b53a53_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['date'], name='teacher_att_date_76820c_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['school', 'date', 'status'], name='teacher_att_school__220df1_idx'),
        ),
    ]
