# Generated by Django 5.2.8 on 2026-01-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_schools',
            field=models.ManyToManyField(blank=True, related_name='allotted_teachers', to='schools.school'),
        ),
    ]
