# Generated by Django 4.2.9 on 2026-04-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_teacher_assigned_schools"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["employee_id"], name="teachers_employe_e16945_idx"
            ),
        ),
    ]
