# Generated by Django 4.2.9 on 2026-04-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="institution_type",
            field=models.CharField(
                choices=[
                    ("K12_SCHOOL", "K-12 School"),
                    ("TRAINING_CENTER", "Training/Computer Center"),
                    ("COLLEGE", "College/University"),
                ],
                default="K12_SCHOOL",
                max_length=20,
            ),
        ),
    ]
