# Generated by Django 4.2.9 on 2026-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='institution_type',
            field=models.CharField(choices=[('K12_SCHOOL', 'K-12 School'), ('TRAINING_CENTER', 'Computer/Training Center'), ('INSTITUTE', 'Institute'), ('COLLEGE', 'College/University')], default='K12_SCHOOL', max_length=20),
        ),
    ]
