# Generated by Django 4.2.9 on 2026-04-23 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_closed_for_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_closed_for_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_closed_for_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='approved_by_authority',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='funded_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='geo_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='parent_organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='slogan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='society',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='udise_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='zone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='policy_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='school_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_data', to='schools.school')),
            ],
            options={
                'verbose_name': 'Master Data',
                'verbose_name_plural': 'Master Data',
                'db_table': 'master_data',
                'ordering': ['domain', 'description'],
                'unique_together': {('school', 'domain', 'identifier', 'description')},
            },
        ),
    ]
