# Generated by Django 4.2.9 on 2026-04-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_academicyear_is_closed_for_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='chairman_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='chairman_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='chairman_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
