# Generated by Django 4.2.9 on 2026-04-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_chairman_email_school_chairman_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='application_id_prefix',
            field=models.CharField(default='REG', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='teacher_id_prefix',
            field=models.CharField(default='EMP', max_length=10),
        ),
    ]
