# Generated by Django 4.2.9 on 2026-04-28 04:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_schoolsettings_application_id_prefix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPublicPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#1e40af', max_length=20)),
                ('secondary_color', models.CharField(default='#1e293b', max_length=20)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('about_text', models.TextField(blank=True, help_text='Specific about text for the public page')),
                ('is_published', models.BooleanField(default=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_page', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Public Page',
                'verbose_name_plural': 'School Public Pages',
                'db_table': 'school_public_pages',
            },
        ),
        migrations.CreateModel(
            name='SchoolGalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='schools/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('school_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='schools.schoolpublicpage')),
            ],
            options={
                'verbose_name': 'School Gallery Image',
                'verbose_name_plural': 'School Gallery Images',
                'db_table': 'school_gallery_images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
