# Generated by Django 4.2.9 on 2026-05-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_schoolpublicpage_schoolgalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='board',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('STATE', 'State Board'), ('IB', 'International Baccalaureate'), ('IGCSE', 'IGCSE'), ('WEBEL', 'Webel Affiliation'), ('OTHER_AFFILIATION', 'Other Affiliation')], max_length=50),
        ),
    ]
