# Generated by Django 4.2.9 on 2026-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_school_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='age_cutoff_day',
            field=models.IntegerField(default=1, help_text='Day for age calculation (1-31)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='age_cutoff_month',
            field=models.IntegerField(default=4, help_text='Month for age calculation (1-12)'),
        ),
    ]
