# Generated by Django 4.2.9 on 2026-01-31 04:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('schools', '0001_initial'),
        ('teachers', '0002_teacher_assigned_schools'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('ZOOM', 'Zoom'), ('GOOGLE_MEET', 'Google Meet'), ('MICROSOFT_TEAMS', 'Microsoft Teams'), ('OTHER', 'Other')], default='ZOOM', max_length=20)),
                ('meeting_url', models.URLField()),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('meeting_password', models.CharField(blank=True, max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='schools.school')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='classes.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='subjects.subject')),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='classes.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_classes', to='teachers.teacher')),
            ],
            options={
                'db_table': 'live_classes',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
