# Generated by Django 4.2.9 on 2026-05-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('RECEPTIONIST', 'Receptionist'), ('DRIVER', 'Driver'), ('TRANSPORT_MANAGER', 'Transport Manager'), ('HR', 'HR Manager')], default='STUDENT', max_length=20),
        ),
    ]
