# Generated by Django 4.2.9 on 2025-12-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('schools', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('class_group', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'name')},
        ),
    ]
