# Generated by Django 4.2.9 on 2026-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_type_course_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='max_age',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum age allowed for admission (in years)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='min_age',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum age required for admission (in years)', max_digits=4, null=True),
        ),
    ]
