# Generated by Django 4.2.9 on 2026-02-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_number'], name='students_roll_nu_954626_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'current_class', 'section'], name='students_school__299e83_idx'),
        ),
    ]
