# Generated by Django 4.2.9 on 2026-04-23 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_type_course_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0004_academicyear_is_closed_for_admission_and_more'),
        ('students', '0003_student_students_roll_nu_954626_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_payment_mode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LEFT', 'Left/SLC Generated'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='StudentPromotionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_promoted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROMOTED', 'Promoted'), ('RETAINED', 'Retained')], default='PROMOTED', max_length=20)),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='classes.class')),
                ('from_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='schools.academicyear')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='students.student')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='classes.class')),
                ('to_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='schools.academicyear')),
            ],
            options={
                'db_table': 'student_promotions',
            },
        ),
        migrations.CreateModel(
            name='SchoolLeavingCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slc_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('reason_for_leaving', models.CharField(max_length=255)),
                ('conduct', models.CharField(default='Good', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicyear')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slcs', to='schools.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slc', to='students.student')),
            ],
            options={
                'db_table': 'school_leaving_certificates',
                'ordering': ['-issue_date'],
            },
        ),
    ]
