# Generated by Django 4.2.9 on 2026-04-24 04:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_category_student_fee_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='guardian_phone',
            new_name='father_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.CharField(blank=True, choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('GENERAL', 'General')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_college',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='father_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='father_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='father_office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_organisation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='father_qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='is_single_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='legal_guardian',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_college',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Indian', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_medium',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='second_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='third_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='StudentSibling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('section', models.CharField(blank=True, max_length=20)),
                ('roll', models.CharField(blank=True, max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='students.student')),
            ],
            options={
                'db_table': 'student_siblings',
            },
        ),
    ]
