# Generated by Django 4.2.9 on 2026-04-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/fathers/'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/mothers/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
    ]
