# Generated by Django 4.2.9 on 2026-04-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_father_photo_student_mother_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_performance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='is_guardian_father',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_guardian_mother',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_associated_with',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_principle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='primary_contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='relationship_with_student',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
