# Generated by Django 4.2.9 on 2026-04-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_rename_parent_email_admissionapplication_father_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='father_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/fathers/'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/mothers/'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/photos/'),
        ),
    ]
