# Generated by Django 4.2.9 on 2026-04-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admissionapplication_father_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='academic_performance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='category',
            field=models.CharField(default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_occupation_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_organisation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='is_guardian_father',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='is_guardian_mother',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_associated_with',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='previous_school_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='previous_school_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='previous_school_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='previous_school_medium',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='previous_school_pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='previous_school_principle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='previous_school_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='primary_contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='relationship_with_student',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
