# Generated by Django 4.2.9 on 2026-01-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='gateway_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment Gateway Transaction ID', max_length=100),
        ),
    ]
