# Generated by Django 4.2.9 on 2026-02-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feepayment_gateway_metadata_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feeallocation',
            index=models.Index(fields=['status'], name='fee_allocat_status_4658b5_idx'),
        ),
        migrations.AddIndex(
            model_name='feeallocation',
            index=models.Index(fields=['due_date'], name='fee_allocat_due_dat_d2c050_idx'),
        ),
        migrations.AddIndex(
            model_name='feeallocation',
            index=models.Index(fields=['school', 'status'], name='fee_allocat_school__80244b_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_date'], name='fee_payment_payment_2c0b73_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['school', 'payment_date'], name='fee_payment_school__153f0c_idx'),
        ),
    ]
