# Generated by Django 4.2.9 on 2026-04-24 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_type_course_fields'),
        ('fees', '0003_feeallocation_fee_allocat_status_4658b5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feemaster',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_masters', to='classes.class'),
        ),
    ]
