# Generated by Django 4.2.9 on 2026-04-27 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_alter_admissionapplication_status'),
        ('students', '0008_student_academic_performance_student_category_and_more'),
        ('fees', '0004_feemaster_target_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeallocation',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_allocations', to='admissions.admissionapplication'),
        ),
        migrations.AlterField(
            model_name='feeallocation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_allocations', to='students.student'),
        ),
    ]
