# Generated by Django 4.2.9 on 2025-12-29 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subdomain', models.SlugField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_plan', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=50)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_schools', models.IntegerField(default=1)),
                ('max_students', models.IntegerField(default=100)),
                ('max_teachers', models.IntegerField(default=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email_provider', models.CharField(choices=[('SMTP', 'SMTP'), ('SENDGRID', 'SendGrid'), ('MAILGUN', 'Mailgun'), ('SES', 'Amazon SES')], default='SMTP', max_length=50)),
                ('email_from_name', models.CharField(blank=True, max_length=255)),
                ('email_from_address', models.EmailField(blank=True, max_length=254)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('sms_provider', models.CharField(blank=True, choices=[('TWILIO', 'Twilio'), ('MSG91', 'MSG91'), ('AWS_SNS', 'AWS SNS')], max_length=50)),
                ('sms_api_key', models.CharField(blank=True, max_length=255)),
                ('sms_api_secret', models.CharField(blank=True, max_length=255)),
                ('sms_sender_id', models.CharField(blank=True, max_length=50)),
                ('payment_gateway', models.CharField(blank=True, choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYTM', 'Paytm'), ('PAYPAL', 'PayPal')], max_length=50)),
                ('payment_api_key', models.CharField(blank=True, max_length=255)),
                ('payment_api_secret', models.CharField(blank=True, max_length=255)),
                ('payment_webhook_secret', models.CharField(blank=True, max_length=255)),
                ('default_academic_year', models.CharField(blank=True, max_length=20)),
                ('default_currency', models.CharField(default='INR', max_length=10)),
                ('default_timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('enable_online_admission', models.BooleanField(default=True)),
                ('enable_online_payment', models.BooleanField(default=True)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_live_classes', models.BooleanField(default=False)),
                ('enable_mobile_app', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#6366F1', max_length=7)),
                ('secondary_color', models.CharField(default='#8B5CF6', max_length=7)),
                ('custom_css', models.TextField(blank=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
                'db_table': 'organization_settings',
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Invitation',
                'verbose_name_plural': 'Organization Invitations',
                'db_table': 'organization_invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
