# Generated by Django 4.2.9 on 2026-02-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='subscription_expires_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subscription_plan',
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_schools',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_students',
            field=models.IntegerField(default=999999),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_teachers',
            field=models.IntegerField(default=9999),
        ),
    ]
