# Generated by Django 4.2.9 on 2026-04-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
